Traceback (most recent call last):
  File "/data/database.py", line 60, in <module>
    db = connect_data(data)
         ^^^^^^^^^^^^^^^^^^
  File "/data/database.py", line 29, in connect_data
    with open(filename, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'clients.csv'
