Traceback (most recent call last):
  File "/data/database.py", line 59, in <module>
    data = load_file(path_src)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/database.py", line 10, in load_file
    for files in os.listdir(path_src):
                 ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/backup'
